language: php

sudo: false

branches:
  only:
    - master

php:
  - 5.3

env:
  matrix:
    - CAN_YOU_SEE_THIS=0
    - CAN_YOU_SEE_THIS=1
  global:
    - SHOULD_COVER=$(( $CAN_YOU_SEE_THIS == 1 ? 1 : 0 ))

install:
  - curl -s https://getcomposer.org/installer | php
  - php composer.phar install --no-interaction
  - composer require "phpunit/phpunit=4.8.*"

script:
  - vendor/bin/phpunit test.php
  - echo $SHOULD_COVER
