language: php

sudo: false

branches:
  only:
    - master

php:
  - 5.3

matrix:
  include:
    - env: CAN_YOU_SEE_THIS=1

install:
  - curl -s https://getcomposer.org/installer | php
  - php composer.phar install --no-interaction
  - composer require "phpunit/phpunit=4.8.*"

script:
  - vendor/bin/phpunit test.php
