language: php

sudo: false

branches:
  only:
    - master

php:
  - 7

env:
  matrix:
    - CAN_YOU_SEE_THIS=0
    - CAN_YOU_SEE_THIS=1

install:
  - curl -s https://getcomposer.org/installer | php
  - php composer.phar install --no-interaction
  - composer require "phpunit/phpunit=4.8.*"

before_script:
  - if [[ $CAN_YOU_SEE_THIS = '0' ]]; then SHOULD_COVER=1; else SHOULD_COVER=0; fi

script:
  - vendor/bin/phpunit test.php
  - echo $SHOULD_COVER
  - echo $SUPER_SECRET_STUFF
