language: php

sudo: false

branches:
  only:
    - master

php:
  - 5.3

env:
  global:
    - [[ if $CAN_YOU_SEE_THIS = 1 ]]; then SHOULD_COVER=1; else SHOULD_COVER=0; fi
  matrix:
    - CAN_YOU_SEE_THIS=0
    - CAN_YOU_SEE_THIS=1

install:
  - curl -s https://getcomposer.org/installer | php
  - php composer.phar install --no-interaction
  - composer require "phpunit/phpunit=4.8.*"

script:
  - vendor/bin/phpunit test.php
  - echo $SHOULD_COVER
